---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-st2auth
  annotations:
    description: StackStorm st2auth - all authentication is managed by this service.
  labels:
    app: st2auth
    tier: backend
    vendor: stackstorm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: st2auth
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9100

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-st2api
  annotations:
    description: StackStorm st2api - service hosts the REST API endpoints that serve requests from WebUI, CLI, ChatOps and other st2 services.
  labels:
    app: st2api
    tier: backend
    vendor: stackstorm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: st2api
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9101

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-st2stream
  annotations:
    description: StackStorm st2stream - exposes a server-sent event stream, used by the clients like WebUI and ChatOps to receive update from the st2stream server.
  labels:
    app: st2stream
    tier: backend
    vendor: stackstorm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: st2stream
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9102

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-st2web
  annotations:
    description: StackStorm st2web, - an admin Web UI and main entry point for external API requests
    {{- if .Values.st2web.service.hostname }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.st2web.service.hostname | quote }}
    {{- end }}
    {{- if .Values.st2web.service.annotations }}
      {{- toYaml .Values.st2web.service.annotations | nindent 4 }}
    {{- end }}
  labels:
    app: st2web
    tier: frontend
    vendor: stackstorm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: st2web
    release: {{ .Release.Name }}
  type: {{ .Values.st2web.service.type }}
  {{- if contains "ExternalName" .Values.st2web.service.type }}
  {{- if .Values.st2web.service.hostname }}
  externalName: {{ .Values.st2web.service.hostname }}
  {{- end }}
  {{- end }}
  ports:
  - protocol: TCP
    port: 80

{{ if .Values.st2chatops.enabled -}}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-st2chatops
  annotations:
    description: StackStorm st2chatops, - conversation-driven automation service exposed as hubot instance with predefined list of chat adapters
  labels:
    app: st2chatops
    tier: backend
    vendor: stackstorm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: st2chatops
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8081
{{- end }}
