---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-st2auth{{ template "enterpriseSuffix" . }}
  annotations:
    description: StackStorm st2auth - all authentication is managed by this service.
  labels:
    app: st2auth
    tier: backend
    vendor: stackstorm
    support: {{ template "supportMethod" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: st2auth
    support: {{ template "supportMethod" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9100

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-st2api{{ template "enterpriseSuffix" . }}
  annotations:
    description: StackStorm st2api - service hosts the REST API endpoints that serve requests from WebUI, CLI, ChatOps and other st2 services.
  labels:
    app: st2api
    tier: backend
    vendor: stackstorm
    support: {{ template "supportMethod" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: st2api
    support: {{ template "supportMethod" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9101

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-st2stream{{ template "enterpriseSuffix" . }}
  annotations:
    description: StackStorm st2stream - exposes a server-sent event stream, used by the clients like WebUI and ChatOps to receive update from the st2stream server.
  labels:
    app: st2stream
    tier: backend
    vendor: stackstorm
    support: {{ template "supportMethod" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: st2stream
    support: {{ template "supportMethod" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9102

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-st2web{{ template "enterpriseSuffix" . }}
  annotations:
    description: StackStorm st2web, - an admin Web UI and main entry point for external API requests
    {{- if .Values.st2web.service.hostname }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.st2web.service.hostname | quote }}
    {{- end }}
    # For more information, see https://kubernetes.io/docs/concepts/services-networking/service/#ssl-support-on-aws
    {{- if eq .Values.st2web.service.type "LoadBalancer" }}
    {{- if .Values.st2web.service.loadBalancer.sslCert }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.st2web.service.loadBalancer.sslCert | quote }}
    {{- end }}
    {{- if .Values.st2web.service.loadBalancer.backendProtocol }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: {{ .Values.st2web.service.loadBalancer.backendProtocol | quote }}
    {{- end }}
    {{- if .Values.st2web.service.loadBalancer.sslPorts }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: {{ .Values.st2web.service.loadBalancer.sslPorts | quote }}
    {{- end }}
    {{- if .Values.st2web.service.loadBalancer.sslNegotiationPolicy }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: {{ .Values.st2web.service.loadBalancer.sslNegotiationPolicy | quote }}
    {{- end }}
    {{- end }}
  labels:
    app: st2web
    tier: frontend
    vendor: stackstorm
    support: {{ template "supportMethod" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: st2web
    support: {{ template "supportMethod" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.st2web.service.type }}
  ports:
  - protocol: TCP
    port: 443
